const { chromium }=require('playwright-core');
const fs=require('fs'); const path=require('path');
const ROOT='/opt/data/work/flop/agents/quietledger';
const OUT=path.join(ROOT,'receipts/tmp/twitter-account001-finish'); fs.mkdirSync(OUT,{recursive:true});
const CDP=process.env.CDP||'http://127.0.0.1:18801';
const CODE=process.env.X_VERIFY_CODE||'';
const TEXT=`QuietLedger is maintaining a public FLOP / Technocore proof chain: persistent Ed25519 DID, GitHub receipts, and signed evidence that can be checked later.\n\nRepo: https://github.com/FillipMorris/flop-quietledger\n\n@flop_labs Technocore $FLOP`;
function env(){const o={}; for(const l of fs.readFileSync('/opt/data/secure/flop/agents/quietledger/twitter/credentials.env','utf8').split(/\r?\n/)){const m=l.match(/^([A-Z0-9_]+)=(.*)$/i); if(m)o[m[1]]=m[2].replace(/^['"]|['"]$/g,'')} return o}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function body(p){return await p.evaluate(()=>document.body.innerText).catch(()=> '')}
async function setval(p,sel,val){return await p.evaluate(({sel,val})=>{const el=document.querySelector(sel); if(!el) return false; const d=Object.getOwnPropertyDescriptor(Object.getPrototypeOf(el),'value'); d.set.call(el,val); el.dispatchEvent(new InputEvent('input',{bubbles:true,cancelable:true,inputType:'insertText',data:val})); el.dispatchEvent(new Event('change',{bubbles:true})); return true},{sel,val})}
async function clickContinue(p){const target=await p.evaluate(()=>Array.from(document.querySelectorAll('button,[role="button"],div')).map((e,i)=>{const r=e.getBoundingClientRect();return {i,txt:(e.innerText||'').trim(),x:r.x,y:r.y,w:r.width,h:r.height,tag:e.tagName}}).filter(o=>o.txt==='Continue'&&o.w>50&&o.h>10).sort((a,b)=>b.w-a.w)[0]); if(target){await p.mouse.click(target.x+target.w/2,target.y+target.h/2); return target} await p.keyboard.press('Enter'); return null}
async function ensureLogin(p,c){let t=await body(p); if(/Verification code|Check your email/i.test(t)){await p.locator('input[name="challenge_response"],input[name="verification_code"],input[type="text"]').first().click({force:true,timeout:5000}); await p.keyboard.press('Control+A'); await p.keyboard.press('Backspace'); await p.keyboard.type(CODE,{delay:45}); await clickContinue(p); await sleep(8000); t=await body(p)}
 if(/Password|Use password/i.test(t) && !/Invalid code|unexpected error/i.test(t)){await p.getByText(/Use password/i).click({force:true,timeout:1500}).catch(()=>{}); await sleep(700); const pw=p.locator('input[type="password"],input[name="password"]').first(); if(await pw.isVisible({timeout:3000}).catch(()=>false)){await pw.fill(c.TWITTER_PASSWORD||'',{timeout:5000}); await p.keyboard.press('Enter'); await sleep(10000); t=await body(p)}}
 if(!/Home\n|For you|What is happening|Post/.test(t) || /Log in|Sign in|Confirm your account|Verification code|Check your email|Invalid code/i.test(t)) throw new Error('login_not_confirmed:'+t.slice(0,220).replace(/\s+/g,' '));}
async function postNew(p,user){await p.goto('https://x.com/compose/post',{waitUntil:'domcontentloaded',timeout:60000}); await sleep(4500); await p.getByText('Accept all cookies').click({force:true,timeout:1000}).catch(()=>{}); const box=p.locator('[data-testid="tweetTextarea_0"][role="textbox"],div[aria-label="Post text"][role="textbox"]').first(); await box.click({force:true,timeout:10000}); await p.keyboard.insertText(TEXT); await sleep(1500); const states=await p.locator('[data-testid="tweetButton"], [data-testid="tweetButtonInline"]').evaluateAll(bs=>bs.map(b=>({test:b.getAttribute('data-testid'),disabled:b.disabled,txt:b.innerText}))).catch(e=>[{error:String(e)}]); fs.writeFileSync(path.join(OUT,'post-button-state.json'),JSON.stringify(states,null,2)); await p.locator('[data-testid="tweetButton"], [data-testid="tweetButtonInline"]').filter({hasText:/Post/i}).first().click({force:true,timeout:12000}); await sleep(9000); await p.goto('https://x.com/'+user,{waitUntil:'domcontentloaded',timeout:60000}); await sleep(7000); let url=null; for(let pass=0;pass<4&&!url;pass++){const n=await p.locator('article').count().catch(()=>0); for(let i=0;i<Math.min(n,10);i++){const a=p.locator('article').nth(i); const tx=await a.innerText({timeout:1500}).catch(()=> ''); if(tx.includes('QuietLedger is maintaining')&&tx.includes('flop-quietledger')){const links=await a.locator('a[href*="/status/"]').evaluateAll(els=>els.map(e=>e.href)).catch(()=>[]); url=links.find(h=>h.includes('/status/'))||null; break}} if(!url){await p.mouse.wheel(0,700); await sleep(1500)}} return url}
async function followLike(p){let followed=false; const liked=[]; await p.goto('https://x.com/flop_labs',{waitUntil:'domcontentloaded',timeout:60000}); await sleep(5000); if(await p.locator('[data-testid$="-follow"]').first().isVisible({timeout:2500}).catch(()=>false)){followed=await p.locator('[data-testid$="-follow"]').first().click({force:true,timeout:5000}).then(()=>true).catch(()=>false); await sleep(2500)} for(const url of ['https://x.com/flop_labs','https://x.com/search?q=Technocore%20FLOP&src=typed_query&f=live']){await p.goto(url,{waitUntil:'domcontentloaded',timeout:60000}); await sleep(5000); const n=await p.locator('article [data-testid="like"]').count().catch(()=>0); let did=0; for(let i=0;i<Math.min(n,2);i++){if(await p.locator('article [data-testid="like"]').nth(i).click({force:true,timeout:3000}).then(()=>true).catch(()=>false)){did++; await sleep(1000)}} liked.push({url,liked:did})} return {followed,liked}}
(async()=>{const c=env(); const user=(c.TWITTER_USERNAME||'').replace(/^@/,''); const b=await chromium.connectOverCDP(CDP,{timeout:15000}); const ctx=b.contexts()[0]; const p=ctx.pages().filter(x=>/x\.com/.test(x.url())).pop()||await ctx.newPage(); await ensureLogin(p,c); const social=await followLike(p); const new_post_url=await postNew(p,user); const result={ok:!!new_post_url,user,new_post_url,followed_flop_labs:social.followed,liked:social.liked,text:TEXT,cdp:CDP,profile:'account-001',artifacts_dir:OUT,ts:new Date().toISOString()}; fs.writeFileSync(path.join(OUT,'x-result.json'),JSON.stringify(result,null,2)); console.log(JSON.stringify(result,null,2)); process.exit(result.ok?0:2)})().catch(e=>{const r={ok:false,error:String(e.message||e),cdp:CDP,profile:'account-001',artifacts_dir:OUT,ts:new Date().toISOString()}; fs.writeFileSync(path.join(OUT,'x-error.json'),JSON.stringify(r,null,2)); console.log(JSON.stringify(r,null,2)); process.exit(1)});
